version: '3.8'

services:
  middleware:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MODULE_NAME=main
      - VARIABLE_NAME=app
      - ENVIRONMENT=${ENVIRONMENT}
      - KAFKA_TOPICS=${KAFKA_TOPICS}
    env_file:
      - .env